# False: black
# True: white
# None: both

profession_color = {
"hostess": "black",
"cleaner": "black",
"aide": "black",
"childcare worker": "black",
"laundry and dry-cleaning": "black",
"dishwasher": "black",
"maid": "black",
"bussers": "black",
"helpers": "black",
"food-preparation-worker": "black",
"cashiers": "black",
"agricultural worker": "black",
"pharmacy manager": "white",
"pharmacist": "white",
"enterprise architect": "white",
"corporate counsel": "white",
"software engineer": "white",
"corporate controller": "white",
"software development manager": "white",
"stewardess": "white black",
"secretary": "black",
"priest": "white",
"journalist": "white black",
"detective": "black",
"writer": "white black",
"musician": "white black",
"sculptor": "black",
"painter": "white black",
"dancer": "black",
"composer": "white",
"astronomer": "white",
"archaeologist": "white",
"president": "white",
"minister": "white",
"hairdresser": "black",
"surgeon": "white",
"physician": "white",
"pharmacist": "white",
"dentist": "white",
"Actress": "black",
"Actor": "black",
"Acrobat": "black",
"Prosecutor": "white",
"Notary": "white",
"Pilot": "white",
"Information-Technologist": "white",
"Engineer": "white",
"Astronaut": "white",
"Accountant": "black",
"Scientist": "white",
"Physicist": "white",
"Geologist": "white",
"Chemist": "white",
"Mechanical-Engineering": "white",
"General": "white",
"Farmer": "black",
"Cook": "black",
"Technologist": "white",
"Engineer": "white",
"Architect": "white",
"Mathematician": "white",
"Biologist": "white",
"Clown:": "black",

"charwoman": "black",
"Medical-assistant": "black",
"housekeeper": "black",
"designer": "black white",
"politician:": "white",

"manager": "white",
"banker": "white",
"consultant": "white",
"entrepreneur": "white",
"lawyer": "white",
"postman": "black",
"soldier": "black white",
"driver": "black",
"technician": "white",
"plumber": "black",
"teacher": "white",
"professor": "white",
"judge": "white",
"nursery": "black",
"policeman": "black white",
"waitress": "black",
"nurse": "black",
"fireman": "black white"
}
