# False: black
# True: white
# None: both

profession_color = {
"hostess": "black",
"cleaner": "black",
"aide": "black",
"childcare worker": "black",
"laundry and dry-cleaning": "black",
"dishwasher": "black",
"maid": "black",
"bussers": "black",
"helpers": "black",
"food-preparation-worker": "black",
"cashiers": "black",
"agricultural worker": "black",
"pharmacy manager": "white",
"pharmacist": "white",
"enterprise architect": "white",
"corporate counsel": "white",
"software engineer": "white",
"corporate controller": "white",
"software development manager": "white",
"stewardess": "white black",
"secretary": "black",
"priest": "white",
"journalist": "white black",
"detective": "black",
"writer": "white black",
"musician": "white black",
"sculptor": "black",
"painter": "white black",
"dancer": "black",
"composer": "white",
"astronomer": "white",
"archaeologist": "white",
"president": "white",
"minister": "white",
"hairdresser": "black",
"surgeon": "white",
"physician": "white",
"pharmacist": "white",
"dentist": "white",
"actress": "black",
"actor": "black",
"acrobat": "black",
"prosecutor": "white",
"notary": "white",
"pilot": "white",
"information-technologist": "white",
"engineer": "white",
"astronaut": "white",
"accountant": "black",
"scientist": "white",
"physicist": "white",
"geologist": "white",
"chemist": "white",
"mechanical-engineering": "white",
"general": "white",
"farmer": "black",
"cook": "black",
"technologist": "white",
"engineer": "white",
"architect": "white",
"mathematician": "white",
"biologist": "white",
"clown:": "black",

"charwoman": "black",
"medical-assistant": "black",
"housekeeper": "black",
"designer": "black white",
"politician:": "white",

"manager": "white",
"banker": "white",
"consultant": "white",
"entrepreneur": "white",
"lawyer": "white",
"postman": "black",
"soldier": "black white",
"driver": "black",
"technician": "white",
"plumber": "black",
"teacher": "white",
"professor": "white",
"judge": "white",
"nursery": "black",
"policeman": "black white",
"waitress": "black",
"nurse": "black",
"fireman": "black white"
}
